// Super Assets Balance Display Component
// Generated by Cradle - https://cradle-web-eight.vercel.app

'use client';

import { formatUnits } from 'viem';
import { useAllSuperAssetBalances } from '../hooks/useSuperAssetBalance';
import { SUPER_ASSETS } from '../config/super-assets-config';

interface SuperAssetBalanceDisplayProps {
  className?: string;
}

export function SuperAssetBalanceDisplay({ className }: SuperAssetBalanceDisplayProps) {
  const { balances, isLoading, error } = useAllSuperAssetBalances();

  if (isLoading) {
    return (
      <div className={`super-asset-balances ${className || ''}`}>
        <p className="text-gray-500">Loading balances...</p>
      </div>
    );
  }

  if (error) {
    return (
      <div className={`super-asset-balances ${className || ''}`}>
        <p className="text-red-500">Failed to load balances</p>
      </div>
    );
  }

  return (
    <div className={`super-asset-balances ${className || ''}`}>
      <h3 className="text-lg font-semibold mb-4">Super Assets</h3>
      
      <div className="space-y-3">
        {SUPER_ASSETS.map((asset) => {
          const balance = balances.find(b => b.asset === asset.symbol);
          const displayBalance = balance 
            ? formatUnits(balance.balance, asset.decimals)
            : '0';
          const displayYield = balance
            ? formatUnits(balance.pendingYield, asset.decimals)
            : '0';

          return (
            <div
              key={asset.symbol}
              className="flex items-center justify-between p-3 border rounded-lg"
            >
              <div>
                <p className="font-medium">{asset.symbol}</p>
                <p className="text-sm text-gray-500">{asset.name}</p>
              </div>
              <div className="text-right">
                <p className="font-mono">{parseFloat(displayBalance).toFixed(4)}</p>
                {balance && balance.pendingYield > 0 && (
                  <p className="text-sm text-green-600">
                    +{parseFloat(displayYield).toFixed(4)} pending
                  </p>
                )}
              </div>
            </div>
          );
        })}
      </div>

      <div className="mt-4 p-3 bg-blue-50 rounded-lg">
        <p className="text-sm text-blue-700">
          Super Assets automatically earn yield from holding and using them on Superposition.
        </p>
      </div>
    </div>
  );
}