// Super Asset Yield Tracking Hook
// Generated by Cradle - https://cradle-web-eight.vercel.app

'use client';

import { useCallback } from 'react';
import { useAccount, usePublicClient, useWalletClient } from 'wagmi';
import { useQuery } from '@tanstack/react-query';
import type { SuperAssetSymbol, YieldData } from '../types/super-assets';
import { SUPER_ASSET_ABI } from '../abi/super-assets';
import { getSuperAssetAddress } from '../config/super-assets-config';

/**
 * Hook for tracking yield on a Super Asset
 */
export function useSuperAssetYield(asset: SuperAssetSymbol) {
  const { address } = useAccount();
  const publicClient = usePublicClient();
  const { data: walletClient } = useWalletClient();

  const superAssetAddress = getSuperAssetAddress(asset);

  const { data: yieldData, isLoading, error, refetch } = useQuery({
    queryKey: ['super-asset-yield', asset, address],
    queryFn: async (): Promise<YieldData | null> => {
      if (!address || !publicClient) return null;

      try {
        const pendingYield = await publicClient.readContract({
          address: superAssetAddress,
          abi: SUPER_ASSET_ABI,
          functionName: 'pendingYield',
          args: [address],
        });

        // In production, would fetch historical data from an indexer
        return {
          asset,
          currentApy: 5.5, // Would fetch from API
          totalYieldEarned: BigInt(0), // Would calculate from history
          pendingYield: BigInt(pendingYield),
          lastClaimTimestamp: 0,
          yieldHistory: [],
        };
      } catch (err) {
        console.error('Failed to fetch yield data:', err);
        return null;
      }
    },
    enabled: !!address && !!publicClient,
    refetchInterval: 30_000, // Refetch every 30 seconds
  });

  /**
   * Claim pending yield
   */
  const claimYield = useCallback(async (): Promise<string | null> => {
    if (!address || !walletClient || !publicClient) return null;

    try {
      const hash = await walletClient.writeContract({
        address: superAssetAddress,
        abi: SUPER_ASSET_ABI,
        functionName: 'claimYield',
        args: [],
      });

      await publicClient.waitForTransactionReceipt({ hash });
      refetch();
      return hash;
    } catch (err) {
      console.error('Failed to claim yield:', err);
      return null;
    }
  }, [address, walletClient, publicClient, superAssetAddress, refetch]);

  return {
    yieldData,
    pendingYield: yieldData?.pendingYield ?? BigInt(0),
    currentApy: yieldData?.currentApy ?? 0,
    isLoading,
    error,
    claimYield,
    refetch,
  };
}

/**
 * Hook for tracking yield across all Super Assets
 */
export function useAllSuperAssetsYield() {
  const { address } = useAccount();
  const publicClient = usePublicClient();

  const { data: yields, isLoading, error, refetch } = useQuery({
    queryKey: ['all-super-assets-yield', address],
    queryFn: async () => {
      if (!address || !publicClient) return [];

      // Would fetch yield data for all Super Assets
      return [];
    },
    enabled: !!address && !!publicClient,
    refetchInterval: 60_000,
  });

  const totalPendingYield = yields?.reduce(
    (sum, y) => sum + (y.pendingYield ?? BigInt(0)),
    BigInt(0)
  ) ?? BigInt(0);

  return {
    yields: yields ?? [],
    totalPendingYield,
    isLoading,
    error,
    refetch,
  };
}