// Super Assets Types
// Generated by Cradle - https://cradle-web-eight.vercel.app

import type { Address } from 'viem';

/**
 * Supported Super Assets
 */
export type SuperAssetSymbol = 'sUSDC' | 'sETH' | 'sWETH';

/**
 * Super Asset information
 */
export interface SuperAsset {
  symbol: SuperAssetSymbol;
  name: string;
  address: Address;
  underlyingAddress: Address;
  underlyingSymbol: string;
  decimals: number;
  apy: number; // Current APY percentage
  totalSupply: bigint;
  exchangeRate: bigint; // Rate of Super Asset to underlying
}

/**
 * User's Super Asset balance
 */
export interface SuperAssetBalance {
  asset: SuperAssetSymbol;
  balance: bigint;
  underlyingValue: bigint;
  pendingYield: bigint;
  totalYieldEarned: bigint;
}

/**
 * Yield tracking data
 */
export interface YieldData {
  asset: SuperAssetSymbol;
  currentApy: number;
  totalYieldEarned: bigint;
  pendingYield: bigint;
  lastClaimTimestamp: number;
  yieldHistory: YieldHistoryEntry[];
}

/**
 * Historical yield entry
 */
export interface YieldHistoryEntry {
  timestamp: number;
  amount: bigint;
  txHash: string;
}

/**
 * Wrap/unwrap operation status
 */
export type WrapStatus =
  | 'idle'
  | 'approving'
  | 'wrapping'
  | 'unwrapping'
  | 'completed'
  | 'error';